/**
 * Inlines every EJS template into a generated TypeScript module.
 *
 * Cloudflare Workers have no persistent filesystem, so views cannot be read
 * from disk at render time the way Express normally does. This bakes them into
 * the bundle instead; `src/lib/views.ts` compiles from the resulting map.
 *
 * Relative `include()` paths are rewritten to root-absolute ones on the way
 * through. EJS resolves a *relative* include by probing the filesystem first,
 * which cannot work here; an *absolute* one is resolved with plain path
 * arithmetic against `root`, so it never touches node:fs.
 *
 * Run via `pnpm --filter @workspace/shiftlist run gen:views`.
 */
import { readdir, readFile, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const artifactDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const viewsDir = path.join(artifactDir, "views");
const outFile = path.join(artifactDir, "src/generated/views.ts");

/** Every `.ejs` file under `viewsDir`, as POSIX paths relative to it. */
async function collect(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const found = [];

  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      found.push(...(await collect(full)));
    } else if (entry.name.endsWith(".ejs")) {
      found.push(path.relative(viewsDir, full).split(path.sep).join("/"));
    }
  }

  return found.sort();
}

// Matches include('x'), include("x", {...}) and include(`x`) — string literals only.
const INCLUDE = /(\binclude\s*\(\s*)(['"`])([^'"`]+)\2/g;
// Any include() whose argument is not a plain string literal.
const DYNAMIC_INCLUDE = /\binclude\s*\(\s*(?!['"`])/;

function rewriteIncludes(source, viewKey) {
  if (DYNAMIC_INCLUDE.test(source)) {
    throw new Error(
      `${viewKey}: include() with a non-literal path cannot be resolved at build time.`,
    );
  }

  const dir = path.posix.dirname(viewKey);

  return source.replace(INCLUDE, (_match, head, quote, target) => {
    const absolute = target.startsWith("/")
      ? target
      : path.posix.resolve("/", dir, target);
    return `${head}${quote}${absolute}${quote}`;
  });
}

const files = await collect(viewsDir);

if (files.length === 0) {
  console.error(`No .ejs templates found under ${viewsDir}`);
  process.exit(1);
}

const entries = await Promise.all(
  files.map(async (key) => {
    const source = rewriteIncludes(await readFile(path.join(viewsDir, key), "utf8"), key);
    return `  ${JSON.stringify(key)}: ${JSON.stringify(source)},`;
  })
);

const contents = `// Generated by scripts/gen-views.mjs — do not edit.
// Keys are POSIX paths relative to artifacts/shiftlist/views.

export const VIEWS: Record<string, string> = {
${entries.join("\n")}
};
`;

await mkdir(path.dirname(outFile), { recursive: true });
await writeFile(outFile, contents, "utf8");

console.log(`gen-views: inlined ${files.length} templates → ${path.relative(artifactDir, outFile)}`);
